--------------------------------------------------------
--  File created - Thursday-June-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURTBOOKING
--------------------------------------------------------

  CREATE TABLE "COURT"."COURTBOOKING" 
   (	"COURTID" NUMBER(10,0), 
	"CUSTIC" VARCHAR2(20 BYTE), 
	"BOOK_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COURT.COURTBOOKING
SET DEFINE OFF;
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (3,'940529115632','2');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (5,'940529115632','2');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (1,'95011295677','3');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (2,'95011295677','3');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (4,'95011295677','3');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (5,'95011295677','3');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (7,'95011295677','3');
Insert into COURT.COURTBOOKING (COURTID,CUSTIC,BOOK_ID) values (3,'950112982345','4');
--------------------------------------------------------
--  DDL for Index COURTBOOKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COURT"."COURTBOOKING_PK" ON "COURT"."COURTBOOKING" ("CUSTIC", "BOOK_ID", "COURTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COURTBOOKING
--------------------------------------------------------

  ALTER TABLE "COURT"."COURTBOOKING" ADD CONSTRAINT "COURTBOOKING_PK" PRIMARY KEY ("CUSTIC", "BOOK_ID", "COURTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COURT"."COURTBOOKING" MODIFY ("CUSTIC" NOT NULL ENABLE);
  ALTER TABLE "COURT"."COURTBOOKING" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "COURT"."COURTBOOKING" MODIFY ("COURTID" NOT NULL ENABLE);
