--------------------------------------------------------
--  File created - Thursday-June-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURTS
--------------------------------------------------------

  CREATE TABLE "COURT"."COURTS" 
   (	"COURTID" NUMBER(10,0), 
	"COURTTYPE" VARCHAR2(30 BYTE), 
	"COURTPRICE" NUMBER(6,2), 
	"COURTEQUIPMENT" VARCHAR2(20 BYTE), 
	"COURTROOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COURT.COURTS
SET DEFINE OFF;
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (2,'futsal',10,'yes','2');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (3,'futsal',10,'yes','7');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (4,'futsal',10,'no','4');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (5,'badminton',12,'no','1');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (6,'badminton',12,'yes','2');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (7,'badminton',12,'yes','3');
Insert into COURT.COURTS (COURTID,COURTTYPE,COURTPRICE,COURTEQUIPMENT,COURTROOM) values (1,'tennis',20,'no','room 6');
--------------------------------------------------------
--  DDL for Index COURTID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COURT"."COURTID_PK" ON "COURT"."COURTS" ("COURTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger COURTTRI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "COURT"."COURTTRI" 
   before insert on "COURT"."COURTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."COURTID" is null then 
         select COURTID_SEQQ.nextval into :NEW."COURTID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "COURT"."COURTTRI" ENABLE;
--------------------------------------------------------
--  Constraints for Table COURTS
--------------------------------------------------------

  ALTER TABLE "COURT"."COURTS" ADD CONSTRAINT "COURTID_PK" PRIMARY KEY ("COURTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COURT"."COURTS" MODIFY ("COURTROOM" CONSTRAINT "COURTROOM_NN" NOT NULL ENABLE);
  ALTER TABLE "COURT"."COURTS" MODIFY ("COURTEQUIPMENT" CONSTRAINT "COURTEQUIPMENT_NN" NOT NULL ENABLE);
  ALTER TABLE "COURT"."COURTS" MODIFY ("COURTPRICE" CONSTRAINT "COURTPRICE_NN" NOT NULL ENABLE);
  ALTER TABLE "COURT"."COURTS" MODIFY ("COURTTYPE" CONSTRAINT "COURTTYPE_NN" NOT NULL ENABLE);
