--------------------------------------------------------
--  File created - Thursday-June-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURT_NONMEMBERS
--------------------------------------------------------

  CREATE TABLE "COURT"."COURT_NONMEMBERS" 
   (	"CUSTIC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COURT.COURT_NONMEMBERS
SET DEFINE OFF;
Insert into COURT.COURT_NONMEMBERS (CUSTIC) values ('9301156344');
Insert into COURT.COURT_NONMEMBERS (CUSTIC) values ('940529115634');
Insert into COURT.COURT_NONMEMBERS (CUSTIC) values ('950112982345');
--------------------------------------------------------
--  DDL for Index COURT_NONMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COURT"."COURT_NONMEMBERS_PK" ON "COURT"."COURT_NONMEMBERS" ("CUSTIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COURT_NONMEMBERS
--------------------------------------------------------

  ALTER TABLE "COURT"."COURT_NONMEMBERS" ADD CONSTRAINT "COURT_NONMEMBERS_PK" PRIMARY KEY ("CUSTIC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COURT"."COURT_NONMEMBERS" MODIFY ("CUSTIC" NOT NULL ENABLE);
