--------------------------------------------------------
--  File created - Thursday-June-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "COURT"."STAFF" 
   (	"STAFFID" NUMBER, 
	"STAFFNAME" VARCHAR2(50 BYTE), 
	"PHONENO" VARCHAR2(50 BYTE), 
	"MANAGERID" NUMBER DEFAULT null, 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COURT.STAFF
SET DEFINE OFF;
Insert into COURT.STAFF (STAFFID,STAFFNAME,PHONENO,MANAGERID,EMAIL,PASSWORD) values (5,'syafiqah','012345678',3,'syaf@gmail.com','b59c67bf196a4758191e42f76670ceba');
Insert into COURT.STAFF (STAFFID,STAFFNAME,PHONENO,MANAGERID,EMAIL,PASSWORD) values (1,'Amran','0122344',3,'lm@yahoo.com','3b712de48137572f3849aabd5666a4e3');
Insert into COURT.STAFF (STAFFID,STAFFNAME,PHONENO,MANAGERID,EMAIL,PASSWORD) values (3,'Ain','01292993883',null,'aln@yahoo.com','3b712de48137572f3849aabd5666a4e3');
Insert into COURT.STAFF (STAFFID,STAFFNAME,PHONENO,MANAGERID,EMAIL,PASSWORD) values (4,'admin','097777433',null,'admin@gmail.com','81dc9bdb52d04dc20036dbd8313ed055');
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COURT"."STAFF_PK" ON "COURT"."STAFF" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger STAFF_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "COURT"."STAFF_TRG" BEFORE INSERT ON STAFF 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.STAFFID IS NULL THEN
      SELECT STAFF_SEQ1.NEXTVAL INTO :NEW.STAFFID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COURT"."STAFF_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "COURT"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COURT"."STAFF" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "COURT"."STAFF" MODIFY ("STAFFID" NOT NULL ENABLE);
